buildscript {
	repositories {
		mavenCentral()
		maven { url 'https://cdn.fox2code.com/maven' }
		maven { url 'https://jitpack.io/' }
	}
	dependencies {
		classpath 'com.fox2code.FoxLoader:dev:2.0-alpha35'
	}
}

apply plugin: 'foxloader.dev'

version '0.1.0'

foxloader {
	modId = 'chlorojoules'
	modName = 'ChloroJoules'
	modVersion = project.version
	modAuthors = 'Emily "TTG" Banerjee <prs.ttg+cj@pm.me>'
	modWebsite = 'https://chlorojoules.github.io/'
	modMain = 'io.github.chlorojoules.CJMod'
	modIcon = 'textures/items/cj_jewel_awakened.png'
	modDesc = new File('README.md').text
			.replace('\r', '')
			.replace('# ChloroJoules\n', '')
			.replace('*', '')
}
